### ISSUE TITLE
Add compile instructions

### ISSUE THREAD

**Issue by NicoHood** [arduino/listSerialPortsC#1]
I am trying to compile this on arm. It would be nice to add a litle note how to download and compile it. what dependencies are required? Also I currently got problems with the submodule:

``` bash
$ git submodule update --init --recursive
Cloning into 'libserialport'...
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:facchinm/libserialport.git' into submodule path 'libserialport' failed
```

It would be nice if you can add ARM builds natively from arduino too.

**Comment by NicoHood** [comment]
On x64 I had to install `sudo apt-get install libc6-dev-i386` to get rid of some warnings. However the 32bit configure still failed.

**Comment by facchinm** [comment]
Hi Nico, I merged some of your commits and a added proper README
Feel free to test it in your Ubuntu environment!
In the meanwhile, I've uploaded version 1.0.7 with ARM binary included :smile:

**Comment by NicoHood** [comment]
Thx for those fixes! I will try it. If it does not work, I will comment again.

Where did you upload it? You should tag the versions on github and also provide the binaries as well. Or link to the arduino.cc download page. I am a bit confused because the latest git only has 1.0.5, not 1.0.7.

Did you also had a look into the [arduino-builder arm package](https://github.com/arduino/arduino-builder/issues/79#issuecomment-173298515)? Only a **small folder structure** change is required to make the package working. It would be extremely nice if you can fix this as well.

**Comment by NicoHood** [comment]
I still got the `configure: error: C compiler cannot create executables` error. I installed all suggested packages on x64.

**Comment by facchinm** [comment]
Very strange problem... I fired up an Ubuntu minimal VM to understand all the requirement and it works great. I believe it's a problem related with multilibs but, not being an Ubuntu user, I can't help more than that, sorry.
