### ISSUE TITLE
FreeBSD Compilation

### ISSUE THREAD

**Issue by kevans91** [arduino/listSerialPortsC#6]
Hello!

I'm interested in getting an up-to-date build of the arduino suite running on FreeBSD natively, and I'd like to start here. 

Cross-compiling for FreeBSD is going to be a little bit more of a bear -- would it be okay/wise if I make a PR to include a compile_freebsd.sh script that explicitly does _not_ get invoked in pack_and_release.sh?

My goal at this point is to modify the Arduino build system so that its dependencies can/will get built rather than downloaded on systems that are not currently being cross-compiled for.

**Comment by facchinm** [comment]
Hi Kyle!
Sure, feel free to post the PR, not including it in the pack_and_release is the best thing to do!
The IDE build system was borrowed from Processing, so Java was the main target, but is evolving towards a collection of standalone utilities which must be prebuilt... So a complete (from scratch) build system would be awesome! Keep us posted about your progress! Thx

**Comment by kevans91** [comment]
That's an interesting thought...any particular ideas you would entertain for a new build system? I would naturally lean towards CMake, myself, but I know that's not generally the most friendly system, either.

**Comment by facchinm** [comment]
I'd personally go for gradle, so you could compile both the java codebase and the c/c++ projects. I don't know if it supports golang but existing makefiles/build scripts could be executed "out of build"

**Comment by kevans91** [comment]
Alright- thanks!
