### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by kevans91** [arduino/listSerialPortsC#8]
Hello!

I'm somewhat ignorant as far as licensing goes, but can you please clarify the licensing on the bits of code present in this repository? Are these assumed to be LGPL3+ in the spirit of libserialport?

**Comment by facchinm** [comment]
This repo is almost only composed by scripts so I don't know if LGPL3 would apply. If it doesn't, I believe that "public domain" or WTFPL licenses are ok :smile:

**Comment by kevans91** [comment]
My main concern was for {main,jnilib}.c, since we're compiling+packaging those into a binary+shared lib (without the scripts, as it turns out). =)

**Comment by facchinm** [comment]
Right :smile: I think LGPLv3 is could apply well to the jni wrapper (since it becomes a shared library) , the `main` is being compiled statically only for portability but the same license could apply as well.

**Comment by facchinm** [comment]
Fixed by 0b04d03aea5d14c2d3992d590a1961385842b5bb, thanks!

**Comment by kevans91** [comment]
Thank you! =)
